<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ImapProvider;

class ImapProviderSeeder extends Seeder
{
    public function run()
    {
        $providers = [
            [
                'name' => 'gmail',
                'display_name' => 'Gmail',
                'description' => 'Google Gmail',
                'imap_host' => 'imap.gmail.com',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['gmail.com', 'googlemail.com'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => false,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'outlook',
                'display_name' => 'Outlook / Hotmail',
                'description' => 'Microsoft Outlook',
                'imap_host' => 'outlook.office365.com',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['outlook.com', 'hotmail.com', 'live.com', 'msn.com'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => false,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'yahoo',
                'display_name' => 'Yahoo Mail',
                'description' => 'Yahoo Mail',
                'imap_host' => 'imap.mail.yahoo.com',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['yahoo.com', 'yahoo.fr', 'ymail.com', 'rocketmail.com'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => false,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'laposte',
                'display_name' => 'La Poste',
                'description' => 'Messagerie La Poste française',
                'imap_host' => 'imap.laposte.net',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['laposte.net'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'orange',
                'display_name' => 'Orange',
                'description' => 'Messagerie Orange France',
                'imap_host' => 'imap.orange.fr',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['orange.fr', 'wanadoo.fr'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'sfr',
                'display_name' => 'SFR',
                'description' => 'Messagerie SFR',
                'imap_host' => 'imap.sfr.fr',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['sfr.fr', 'neuf.fr', 'cegetel.net'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'free',
                'display_name' => 'Free',
                'description' => 'Messagerie Free',
                'imap_host' => 'imap.free.fr',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['free.fr'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'zoho',
                'display_name' => 'Zoho Mail',
                'description' => 'Zoho Mail service',
                'imap_host' => 'imap.zoho.com',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['zoho.com', 'zoho.eu'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'custom',
                'display_name' => 'Serveur personnalisé',
                'description' => 'Configuration IMAP personnalisée',
                'imap_host' => '',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => [],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'webde',
                'display_name' => 'Web.de',
                'description' => 'Web.de German email service',
                'imap_host' => 'imap.web.de',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['web.de'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'gmx',
                'display_name' => 'GMX',
                'description' => 'GMX email service',
                'imap_host' => 'imap.gmx.net',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['gmx.com', 'gmx.de', 'gmx.net'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'amazon_workmail',
                'display_name' => 'Amazon WorkMail',
                'description' => 'Amazon WorkMail service',
                'imap_host' => 'imap.mail.us-east-1.awsapps.com',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => [],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'apple_icloud',
                'display_name' => 'Apple iCloud',
                'description' => 'Apple iCloud Mail',
                'imap_host' => 'imap.mail.me.com',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => ['icloud.com', 'me.com', 'mac.com'],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'ionos',
                'display_name' => 'IONOS',
                'description' => 'IONOS email hosting',
                'imap_host' => 'imap.ionos.fr',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => [],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'ovh',
                'display_name' => 'OVH',
                'description' => 'OVH email hosting',
                'imap_host' => 'ssl0.ovh.net',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => [],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
            [
                'name' => 'gandi',
                'display_name' => 'Gandi',
                'description' => 'Gandi email hosting',
                'imap_host' => 'mail.gandi.net',
                'imap_port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'common_domains' => [],
                'imap_encryption' => 'ssl',
                'requires_app_password' => false,
                'instructions' => null,
                'domains' => null,
                'mx_patterns' => null,
                'is_active' => true,
                'supports_oauth' => false,
                'oauth_provider' => null,
            ],
        ];

        foreach ($providers as $provider) {
            ImapProvider::updateOrCreate(
                ['name' => $provider['name']],
                $provider
            );
        }
    }
}